export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_FAILED = "GET_USER_DETAILS_FAILED";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_COACHES = "RETRIEVE_COACHES";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const RETRIEVE_MANAGERS = "RETRIEVE_MANAGERS";
export const CREATE_MANAGER = "CREATE_MANAGER";
export const UPDATE_MANAGER = "UPDATE_MANAGER";
export const DELETE_MANAGER = "CREATE_MANAGER";
export const RETRIEVE_INSTITUTION = "RETRIEVE_INSTITUTION";
export const GET_INSTITUTION = "GET_INSTITUTION";
export const SET_INSTITUTION = "SET_INSTITUTION";
export const GET_INSTITUTION_FAILED = "GET_INSTITUTION_FAILED";
export const UPDATE_INSTITUTION = "UPDATE_INSTITUTION";
export const LOAD_INSTITUTION_DAYSOFF = "LOAD_INSTITUTION_DAYSOFF";
export const LOAD_INSTITUTION_SCHEDULES = "LOAD_INSTITUTION_SCHEDULES";
export const LOAD_INSTITUTION_ADVANCE_PAYMENT =
  "LOAD_INSTITUTION_ADVANCE_PAYMENT";
export const DELETE_INSTITUTION_SCHEDULES = "DELETE_INSTITUTION_SCHEDULES";
export const LOAD_INSTITUTION_TIMES = "LOAD_INSTITUTION_TIMES";

export const UPDATE_DAYS_AND_SCHEDULES = "UPDATE_DAYS_AND_SCHEDULES";

export const RETRIEVE_COURTS = "RETRIEVE_COURTS";
export const CREATE_COURT = "CREATE_COURT";
export const UPDATE_COURT = "UPDATE_COURT";
export const DELETE_COURT = "DELETE_COURT";
export const CLEAN_COURTS = "CLEAN_COURTS";

export const RETRIEVE_RERVATIONS = "RETRIEVE_RERVATIONS";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";

export const RETRIEVE_PROMOTIONS = "RETRIEVE_PROMOTIONS";
export const CREATE_PROMOTION = "CREATE_PROMOTION";
export const UPDATE_PROMOTION = "UPDATE_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
